apiVersion: v1
kind: Pod
metadata:
  name: environment
  
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: "devops with aws"
    - name: trainer
      value: "shiva kumar"
    - name: duration
      value: "120hrs"