kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
     project: expense
     environment: dev
     module: backend
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port